apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
{{ include "template.labels" . | indent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: selenium/standalone-chrome:3.8.1
        imagePullPolicy: Always
        ports:
        - name: webdriver
          containerPort: 4444
        livenessProbe:
          httpGet:
            path: /status
            port: 4444
        readinessProbe:
          httpGet:
            path: /status
            port: 4444
        resources:
{{ toYaml .Values.resources | indent 10 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
