---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: soxhub/helm
    tag: v2.1.3

inputs:
- name: source-repo

outputs:
- name: target-repo

run:
  path: /bin/sh
  dir: target-repo
  args:
  - -exec
  - |
    ls -la
    helm init -c
    helm repo add linkyard http://charts.linkyard.ch
    for chart in ../source-repo/*/; do
      echo Processing ${chart}...
      rm -rf ${chart}/charts
      helm dependency update $chart
      helm package $chart
    done
    ls -la
