---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: linkyard/helm
    tag: latest

inputs:
- name: source-repo
- name: chart-repo

outputs:
- name: updated-chart-repo

run:
  path: /bin/sh
  args:
  - -exec
  - |
    echo "Cloning charts repo..."
    git clone chart-repo updated-chart-repo

    echo "Updating helm packages.."
    cd updated-chart-repo
    helm init -c
    helm repo add linkyard http://charts.linkyard.ch

    chart=../source-repo/postgres/
    echo "  Processing ${chart}..."
    rm -rf ${chart}/charts
    helm dependency update $chart
    helm package $chart

    for chart in ../source-repo/*/; do
      echo "  Processing ${chart}..."
      rm -rf ${chart}/charts
      helm dependency update $chart
      helm package $chart
    done

    echo "Indexing helm charts..."
    helm repo index . --url http://charts.linkyard.ch

    echo "Committing changes..."
    git status
    git add .
    git config --global user.email "concourse-ci@linkyard.ch"
    git config --global user.name "Concourse CI"
    git commit -m "Updated charts."
    echo "Done."
