#Concourse CI build configuration
---
resources:
- name: source-repo
  type: git
  source:
    uri: https://github.com/linkyard/helm-charts.git
    branch: master

- name: chart-repo
  type: git
  source:
    uri: https://github.com/linkyard/helm-charts.git
    branch: ci-test

jobs:
- name: package
  plan:
  - get: source-repo
    trigger: true
  - get: chart-repo
  - task: package
    file: source-repo/package.yaml
  - put: chart-repo
    params:
      repository: updated-chart-repo
