#Concourse CI build configuration
---
resources:
- name: source-repo
  type: git
  source:
    uri: git@github.com:linkyard/helm-charts.git
    branch: master
    private_key: {{private-repo-key}}

- name: chart-repo
  type: git
  source:
    uri: git@github.com:linkyard/helm-charts.git
    branch: gh-pages
    private_key: {{private-repo-key}}

jobs:
- name: package
  plan:
  - get: source-repo
    trigger: true
  - get: chart-repo
  - task: package
    file: source-repo/package.yaml
  - put: chart-repo
    params:
      repository: updated-chart-repo
