name: confluence
version: 0.0.1
description: Atlassian Confluence with Postgres as the datastore.
keywords:
  - Atlassian
  - Confluence
home: https://github.com/linkyard/helm-charts
maintainers:
  - name: Mario Siegenthaler
    email: mario.siegenthaler@linkyard.ch
