apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
{{ include "labels" . | indent 8 }}
    spec:
      containers:
      - name: jira
        image: cptactionhank/atlassian-jira-service-desk:{{ .Values.jiraVersion }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        - name: X_PROXY_SCHEME
          value: https
        - name: X_PROXY_PORT
          value: "443"
        - name: X_PATH
          value: /
        - name: CATALINA_OPTS
          value: "-Xmx{{ .Values.maxHeap }}"
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 300
          timeoutSeconds: 120
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 3
          timeoutSeconds: 60
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: data
          mountPath: /var/atlassian/jira
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}
