{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
{{- if .Values.ingress.ssl }}
  annotations:
    kubernetes.io/tls-acme: "true"
{{- end }}
spec:
{{- if .Values.ingress.ssl }}
  tls:
  - hosts:
    - {{ template "hostname" . }}
    secretName: {{ template "fullname" . }}-tls
{{- end }}
  rules:
  - host: {{ template "hostname" . }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: http
{{- end }}
