apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
data:
  adminUser: {{ .Values.adminUser | b64enc | quote }}
  adminPassword: {{ default (cat .Release.Name .Chart.Name | sha256sum) .Values.adminPassword  | b64enc | quote }}
