apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  selector:
    app: {{ .Release.Name }}
    component: {{ default .Chart.Name .Values.nameOverride | quote }}
  ports:
  - name: http
    port: 80
    targetPort: http
