{{- if .Values.runSetup }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}setup
  labels:
    job: {{ template "fullname" . }}setup
{{ include "labels" . | indent 4 }}
spec:
  template:
    metadata:
      name: {{ template "fullname" . }}setup
      labels:
{{ include "template.labels" . | indent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
      - name: setup-jira
        image: linkyard/setup-jira-instance:local
        imagePullPolicy: Always
        env:
        - name: JIRA_URL
          value: {{ if .Values.ingress.ssl }}https://{{ else }}http://{{ end}}{{ template "hostname" . }}/
        - name: JIRA_TITLE
          value: {{ .Values.title | quote }}
        - name: LICENSE
          value: {{ .Values.license | quote}}
        - name: ATLASSIAN_USER
          value: {{ .Values.atlassianAccount.name | quote}}
        - name: ATLASSIAN_PASSWORD
          value: {{ .Values.atlassianAccount.password | quote }}
        - name: ATLASSIAN_ORG
          value: {{ .Values.atlassianAccount.organization | quote }}
        - name: PUBLIC_SIGNUP
          value: "false"
        - name: ADMIN_DISPLAYNAME
          value: {{ .Values.adminDisplayName | quote }}
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: adminUser
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: adminPassword
        - name: ADMIN_EMAIL
          value: {{ .Values.adminEmail | quote }}
        - name: DB_TYPE
          value: PostgreSQL
        - name: DB_HOST
          value: {{ template "postgres.fullname" . }}
        - name: DB_POST
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "postgres.fullname" . }}
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "postgres.fullname" . }}
              key: password
        - name: MAIL_PREFIX
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}-mail
              key: prefix
        - name: MAIL_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}-mail
              key: host
        - name: MAIL_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}-mail
              key: port
        - name: MAIL_SECURE
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}-mail
              key: secure
        - name: MAIL_USER
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}-mail
              key: user
        - name: MAIL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}-mail
              key: password
        volumeMounts:
        - name: logs
          mountPath: /usr/src/app/logs
      volumes:
      - name: logs
        hostPath:
          path: /tmp/logs
{{- end -}}
