apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install
data:
  adminUser: {{ .Values.adminUser | b64enc | quote }}
  adminPassword: {{ randAlphaNum 40 | b64enc | quote }}
