apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
{{ include "labels" . | indent 4 }}
data:
  username: {{ "postgres" | b64enc | quote }}
  password: {{ default (cat .Release.Name (default .Chart.Name .Values.nameOverride) | sha256sum) .Values.password  | b64enc | quote }}
