name: jira
version: 0.7.6
description: Atlassian JIRA with Postgres as the datastore.
keywords:
  - Atlassian
  - JIRA
home: https://github.com/linkyard/helm-charts
maintainers:
  - name: Mario Siegenthaler
    email: mario.siegenthaler@linkyard.ch
